Traceback (most recent call last):
  File "C:\Users\WenqingLi\.conda\envs\torch\lib\multiprocessing\connection.py", line 312, in _recv_bytes
    nread, err = ov.GetOverlappedResult(True)
BrokenPipeError: [WinError 109] 管道已结束。
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:/Users/WenqingLi/Documents/GitHub/deep-reinforcement-learning-/test_code/test_MAPPO/train_football.py", line 215, in <module>
    main(sys.argv[1:])
  File "C:/Users/WenqingLi/Documents/GitHub/deep-reinforcement-learning-/test_code/test_MAPPO/train_football.py", line 180, in main
    envs = make_train_env(all_args)
  File "C:/Users/WenqingLi/Documents/GitHub/deep-reinforcement-learning-/test_code/test_MAPPO/train_football.py", line 37, in make_train_env
    return SubprocVecEnv([get_env_fn(i) for i in range(
  File "C:\Users\WenqingLi\Documents\GitHub\deep-reinforcement-learning-\test_code\test_MAPPO\env_wrappers.py", line 254, in __init__
    observation_space, share_observation_space, action_space = self.remotes[0].recv()
  File "C:\Users\WenqingLi\.conda\envs\torch\lib\multiprocessing\connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "C:\Users\WenqingLi\.conda\envs\torch\lib\multiprocessing\connection.py", line 321, in _recv_bytes
    raise EOFError
EOFError