Traceback (most recent call last):
  File "C:\Users\WenqingLi\.conda\envs\torch\lib\multiprocessing\connection.py", line 312, in _recv_bytes
    nread, err = ov.GetOverlappedResult(True)
BrokenPipeError: [WinError 109] 管道已结束。
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:/Users/WenqingLi/Documents/GitHub/deep-reinforcement-learning-/test_code/test_MAPPO/train_football.py", line 215, in <module>
    main(sys.argv[1:])
  File "C:/Users/WenqingLi/Documents/GitHub/deep-reinforcement-learning-/test_code/test_MAPPO/train_football.py", line 200, in main
    runner.run()
  File "C:\Users\WenqingLi\Documents\GitHub\deep-reinforcement-learning-\test_code\test_MAPPO\football_runner.py", line 27, in run
    self.warmup()
  File "C:\Users\WenqingLi\Documents\GitHub\deep-reinforcement-learning-\test_code\test_MAPPO\football_runner.py", line 84, in warmup
    obs = self.envs.reset()
  File "C:\Users\WenqingLi\Documents\GitHub\deep-reinforcement-learning-\test_code\test_MAPPO\env_wrappers.py", line 272, in reset
    obs = [remote.recv() for remote in self.remotes]
  File "C:\Users\WenqingLi\Documents\GitHub\deep-reinforcement-learning-\test_code\test_MAPPO\env_wrappers.py", line 272, in <listcomp>
    obs = [remote.recv() for remote in self.remotes]
  File "C:\Users\WenqingLi\.conda\envs\torch\lib\multiprocessing\connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "C:\Users\WenqingLi\.conda\envs\torch\lib\multiprocessing\connection.py", line 321, in _recv_bytes
    raise EOFError
EOFError